### ISSUE TITLE
Testing for Python 3.12

### ISSUE THREAD

**Issue by NeffIsBack** [Pennyw0rth/NetExec#233]
This issue should document changes that need to be done before we can "officially" support Python 3.12.

So far it looks like everything works just out of the box 🎉 Just some SyntaxWarnings from other packages:
![image](https://github.com/Pennyw0rth/NetExec/assets/61382599/26231d26-1c88-4dca-b920-ea91568580d2)
![image](https://github.com/Pennyw0rth/NetExec/assets/61382599/3c6e39f4-cf12-4852-bb48-d3577b112a17)

**Comment by NeffIsBack** [comment]
Somehow now aardwolf installation fails with poetry complaining about not having rust.

**Comment by noraj** [comment]
> Somehow now aardwolf installation fails with poetry complaining about not having rust.

- https://github.com/skelsec/aardwolf/blob/ca024706c46265f910c572de194bf32c2805f1c6/pyproject.toml#L2
- https://github.com/skelsec/aardwolf/blob/ca024706c46265f910c572de194bf32c2805f1c6/setup.py#L43

**Comment by noraj** [comment]
On BlackArch, we use a virtualenv poetry packaging for netexec instead of using ArchLinux python system packages because there are too much dependencies, for Netexec, updating too often and more importantly sometimes not using the last version for months while breaking changes are introduced in the dependency.

Right now ArchLinux uses python 3.12.4, so to make NetExec work via a poetry install, I had to install system dependencies (rust) in `depends` in the PKGBUILD as poetry can't install them cf. https://github.com/BlackArch/blackarch/pull/4186/files.

**Comment by NeffIsBack** [comment]
Okay makes sense! 
Weird stuff, i could have sworn the last time i tested it on a fresh kali installation it worked. Maybe it is preinstalled nowadays or some dependency installed it

**Comment by NeffIsBack** [comment]
Python 3.12 is working flawlessly, so closing this one
